# Workflow for deploying thelocalblogg to GitHub Pages
name: Deploy thelocalblogg to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: ["main"]
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build thelocalblogg
        run: npm run build

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload the built files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # Assuming the build output is in the dist folder

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
